### ISSUE TITLE
Merge all sources into a single header library

### ISSUE THREAD

**Issue by spaskalev** [spaskalev/buddy_alloc#1]
Single header libraries are much easier for distribution and use

**Comment by DBJDBJ** [comment]
That is well spotted. 

## Also. 

Having a single header library that can be used on Windows, using clang-cl and VisualStudio will win you even more friends.

**Comment by spaskalev** [comment]
The single header library version is now available.

The experimental sbrk backing is still separate - once stabilized it will also be available via a define.
