### ISSUE TITLE
More Compilers Support?

### ISSUE THREAD

**Issue by YunHsiao** [spaskalev/buddy_alloc#13]
Great library, really helped a lot by doing exactly the thing we needed!

Any chance to support more compilers/environments? It's basically pretty straightforward, by making some simple changes we were able to make it work in our target environments: (right now an MSVC cpp project only but soon to be tested on many more platforms)
https://github.com/YunHsiao/buddy_alloc/tree/cpp

Not sure it's the best way to do this, but you are welcomed to take any references!

**Comment by spaskalev** [comment]
Thanks, I am glad to hear that it was helpful. I don't have much experience with MSVC but I have a windows machine and I will try to get it working there.
