### ISSUE TITLE
Make it possible to use buddy_alloc as a library

### ISSUE THREAD

**Issue by jvoisin** [spaskalev/buddy_alloc#16]
It would be nice to be able to use buddy_alloc as a library, and pass it with `LD_PRELOAD` to targets. This would allow to include it in https://github.com/daanx/mimalloc-bench for example :)

**Comment by spaskalev** [comment]
Hey Julien, thank you for your interest in the project! :)

buddy_alloc can already be used as a library, however it is not designed to be a replacement of system malloc. System-wide malloc implementation deal with allocating memory from and to the OS - buddy_alloc only works with pre-allocated space that it can further partition based on requests.

Also, system-wide malloc implementations have to work with multiple threads. Again, this is not a design goal of buddy_alloc - multi-threaded safety is left to users.

Both are these are listed in the design section at https://github.com/spaskalev/buddy_alloc#design and explained in the following rationale section.

Nevertheless, a very minimal malloc-wrapper for buddy_alloc exists under the bench/ directory. It uses a deprecated POSIX call (sbrk) to obtain memory from the OS, does not release it and it does not enforce any kind of multi-threaded safety. I used that to verity buddy_alloc against glibc's default malloc for single-threaded use. It is not meant to be a representative benchmark.

Regards,
Stan
