### ISSUE TITLE
Convincing Use Cases

### ISSUE THREAD

**Issue by DBJDBJ** [spaskalev/buddy_alloc#3]
Are required to give you some authority. For example stack-allocated metadata?

Something like:

```cpp
size_t arena_size = 65536;
/* STACK space for the metadata and for the arena */
void *buddy_metadata = alloca(buddy_sizeof(arena_size));
/* Assumption is this works too ? */
void *buddy_arena = alloca(arena_size);
struct buddy *buddy = buddy_init(buddy_metadata, buddy_arena, arena_size);

/* Allocate using the buddy allocator */
void *data = buddy_malloc(buddy, 2048);

/* freeing not necessary */
```

**Comment by spaskalev** [comment]
Thanks, I've added some thoughts on why would someone use a custom allocator like this one.

On your example, any form of memory (static, stack, or heap-allocated) can be used for both the arena as well as the metadata.

**Comment by DBJDBJ** [comment]
> Thanks, I've added some thoughts on why would someone use a custom allocator like this one.
> 

IoT, medical devices, avionics, [MISRA ](https://rules.sonarsource.com/c/RSPEC-984) and such ...

**Comment by spaskalev** [comment]
To be honest, I wouldn't want to promote this work to any safety-critical areas just yet :) All in due time

**Comment by DBJDBJ** [comment]
I have seen extremely prominent software of dubious quality. Very recently: [C++ from 2013 used by NASA](https://nasa.github.io/fprime/), and such. 

Good work, I am leaving you in peace...
