### ISSUE TITLE
i'm new  in github please tell me how to start disscution with you

### ISSUE THREAD

**Issue by wrapfr33kzz** [spaskalev/buddy_alloc#34]
i'm new  in github please tell me how to start disscution with you

**Comment by spaskalev** [comment]
Hey @wrapfr33kzz - in the github user interface bar there is a discussions tab - you can use that post any topic related to the project, basically as a forum.

**Comment by spaskalev** [comment]
Check the screenshot - two tabs right of Issues.

**Comment by spaskalev** [comment]
And for a chat you may also find me on discord - Stan#1476 

Cheers!
