### ISSUE TITLE
Convincing Benchmarking

### ISSUE THREAD

**Issue by DBJDBJ** [spaskalev/buddy_alloc#4]
Will not ruin this lib. It will just show honestly how slow or fast it is, compared to standard malloc and friends.  And on different platforms, too.

I use and recommend [UBENCH](https://github.com/sheredom/ubench.h). Hint: it is a single header and small but eminently usable.

Thus it will not be a lot of work to repeat the comparisons on all the OS-es that matter.

**Comment by spaskalev** [comment]
Initial benchmarks added as part of the v0.1.1 release - https://github.com/spaskalev/buddy_alloc/releases/tag/v0.1.1 :)
