### ISSUE TITLE
buddy alignment doesn't pass to buddy_init_alignment

### ISSUE THREAD

**Issue by photoszzt** [spaskalev/buddy_alloc#67]
**Describe the bug**
In this line in buddy_embed_alignment, 
https://github.com/spaskalev/buddy_alloc/blob/8332066ae00f139008099a57a7aff656e30c4c59/buddy_alloc.h#L485
Why the alignment are not passed to buddy_init_alignment but using the default alignment value?

**Expected behavior**
I'm not sure this is a bug. But I expect to use buddy_init_alignment instead of buddy_init. 

**To Reproduce**
Provide a minimal code example that demonstrates the bug.

**Comment by spaskalev** [comment]
Thank you, this looks like a bug. I made the following test
```
void test_buddy_embedded_malloc_alignment(void) {
	unsigned char buf[4096];
	struct buddy *buddy;
	start_test;
	buddy = buddy_embed_alignment(buf, 4096, 0);
	assert(buddy == NULL);
	buddy = buddy_embed_alignment(buf, 4096, 4096);
	assert(buddy == NULL);
	buddy = buddy_embed_alignment(buf, 4096, 2048);
	assert(buddy_arena_size(buddy) == 2048);
	buddy = buddy_embed_alignment(buf, 4096, 1024);
	assert(buddy_arena_size(buddy) == 3072);
	buddy = buddy_embed_alignment(buf, 4096, 512);
	assert(buddy_arena_size(buddy) == 3584);
}
```
Which fails with the current HEAD and added https://github.com/spaskalev/buddy_alloc/pull/68 to fix it.

**Comment by spaskalev** [comment]
Closing as fixed

**Comment by photoszzt** [comment]
@spaskalev https://github.com/spaskalev/buddy_alloc/blob/137b302e133468a001f061911f86df70bf0c6d07/buddy_alloc.h#L452
Is this another oversight? The alignment is not passed so the check is using the default which makes the check not effective.
