### ISSUE TITLE
Add a option to allow null "main"

### ISSUE THREAD

**Issue by xtexChooser** [spaskalev/buddy_alloc#76]
https://github.com/spaskalev/buddy_alloc/blob/0b679cd9a567926e28ad333f5f1de64debc90f25/buddy_alloc.h#L443
https://github.com/spaskalev/buddy_alloc/blob/0b679cd9a567926e28ad333f5f1de64debc90f25/buddy_alloc.h#L489

For example, I am writing an OS and manage the whole linear memory with this allocator.
However, this check is also useful to general usages.

Thanks. This is a pretty-good library.

**Comment by spaskalev** [comment]
Thanks for the feedback! These checks are added to assist users but for managing memory that starts at `0` I can see how this can be an issue.

**Comment by xtexChooser** [comment]
ops sorry I found that managing the first page is impossible because `0` will be regarded as allocation failure. Sorry

**Comment by spaskalev** [comment]
> ops sorry I found that managing the first page is impossible because `0` will be regarded as allocation failure. Sorry

Thinking about it, there's no reason not to be able to do this. The allocation logic itself is handled by the tree component and the allocator just maps tree positions to addresses and vice-versa. It is doable to redo the allocator component with a different API (e.g. `struct alloc_result { void * addr; size_t result }`) and still use the zero page.
